### ISSUE TITLE
fix the wallet home directory 

### ISSUE THREAD

**Issue by LeoStehlik** [derogold/wallet-degon-pluton#2]
change user directory to something else than .plutonwallet-degon, however the proposed change by @CapEtn in the app/index.js directory (export const directories = [ ${homedir}/.plutonwallet-degon, ... ) did not create the custom directory and as it was looking for the address book file in the original directory, the wallet failed to start. In order to publish this release before Christmas, I reverted back and will fix for the next RC). It could possibly bork because of the - in the dir name. Needs investigation.

## Expected Behavior

create custom store directory for the address book etc. instead - if the directory set as above, it won’t be created and wallet will not start.

## Possible Solution

investigate if this was a - in the name issue, or this is reffered to somewhere else in the code. 

## Steps to Reproduce (for bugs)

just change the ${homedir}/.plutonwallet to ${homedir}/.plutonwallet-degon and rebuild/start the wallet. 

## Your Environment

tested on MacOS Catalina (build env at the time of porting the Degon-Pluton wallet

**Comment by yuki111888** [comment]
it's most likely because it's referenced in the main process as well

https://github.com/derogold/wallet-degon-pluton/blob/development/app/main.dev.js#L37-40

**Comment by LeoStehlik** [comment]
good, thought it must be somewhere else, but was too lazy to grep through the files further yesterday, knew it will be an easy fix, but did not want to dealy getting the RC out :)
