### ISSUE TITLE
Slow Syncing Issue

### ISSUE THREAD

**Issue by mrnguyen-cn** [derogold/wallet-degon-pluton#3]
## Expected Behavior

I expected the Degon-pluton wallet to sync faster.
DEGO Price to be updated to inform DEGO Hodlers.

## Current Behavior
The wallet takes forever to sync my DEGO hodls and I'm not sure if it's a DEGO node issue or the pluton wallet issue.

## Possible Solution

Fast sync wallet speed.
Easily to migrate from Goldwallet to Degon-pluton without having to manually type in the seed keys.
Fix the issue for the wallet-upgrader.exe so the old wallet for Goldwallet can be upgrade-able for Degon-pluton wallet.
## Your Environment

- Version used : Pluton-Degon v1.2.1
- Operating System and version : Windows 10 Pro

**Comment by LeoStehlik** [comment]
closing, as the there were some performance improvements.
